### ISSUE TITLE
End-to-end learning

### ISSUE THREAD

**Issue by 9yte** [zhuchen03/ConvexPolytopePosioning#3]
Hi,

Thanks in advance for your time. 

We try to reproduce your results in the ''end-to-end'' learning scenario, and unlike "transfer learning", the numbers are very different to what you have put in the paper, and the performance we get is very low. I guess I'm doing something wrong. Something should not be right into the place. Maybe I'm missing a point. I exactly do the following I just pulled your code and ran launch/attack-end2end.sh for target indices from 1 to 10. Only for one target, and only for one victim network, the misclassification happens. Since it's very resource consuming, I just wanted to double check with you, and then run the attack for all 50 targets. It would be great if you help us with this issue. We appreciate that.

**Comment by zhuchen03** [comment]
Hey,

Sorry for costing your time again! And thank you for raising the valuable questions. I do find two things wrong with the version of code you were using.

1. args.end2end is not passed to make_convex_polytope_poisons in craft_poisons_transfer.py! So actually the script is not doing end2end training! As a result, you were not running the approach used for crafting strong poisons for end2end attacks. My original code was too messy and I had to clean it up before uploading to github. I made some mistakes during the process, and because I did not try to reproduce the results with these code, I did not find them.

2. I forgot to mention that in the end2end setting, during retraining, I also used a weight decay of 5e-4. I am not sure how much this affects the results though. You can find the poisons and scripts I used to generate Figure 7 [here](https://www.dropbox.com/s/h5ku9v22eaarqs9/blackbox-end2end-retrain.zip?dl=0). For example, you can use launch-test/end2end-last2-DenseNet121/test-retrain.sh to reproduce the results or play with different hyperparameters for re-train the networks end2end, or check the logs in the same folder to examine the results in Figure 7. Note you can add the numbers at the end of each log to get the total success cases.

I have fixed both issues in the current version. I would appreciate it if you can try it out again!

**Comment by 9yte** [comment]
Oh, thanks. Sorry, I should have checked carefully. Are you sure the new version of the code is working. To me, it seems all models.py (like googlenet.py) are missing a forward method with block argument. In particular, I get the following error:
"""
Traceback (most recent call last):                                                                                          
  File "craft_poisons_transfer.py", line 207, in <module>                                                                   
    net_repeat=args.net_repeat)                                                                                             
  File "/home/hojjat/poison/baseline/ConvexPolytopePosioning/trainer.py", line 193, in make_convex_polytope_poisons         
    block_feats = [feat.detach() for feat in net(x=target, block=True)]                                                     
  File "/home/hojjat/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in call               
    result = self.forward(*input, **kwargs)                                                                                 
  File "/home/hojjat/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward        
    return self.module(*inputs[0], **kwargs[0])                                                                             
  File "/home/hojjat/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in call               
    result = self.forward(*input, **kwargs)                                                                                 
TypeError: forward() got an unexpected keyword argument 'block
'"""

**Comment by zhuchen03** [comment]
Hey,

Sorry again! I did not check the script previously and found some other issues. They have been fixed! 

1. I have not implemented the code to extract feature maps from the last few layers of DenseNet121, which is the default target network for end2end script. As a result, we cannot print the loss in DenseNet121 as a target network during training. I simply changed the script to use ResNet18 as the target network. 

2. There was a bug in get_CP_loss_end2end, which did not handle the shapes correctly. I don't know why I did not follow my previous code... And I have fixed it now.

I have run the new code for a few iterations and saw the loss reducing. Please try it again, thank you!
